---@type jetbrains.Extra
return {
  ext = "",
  render = function(c, ansi, name)
    local lines = {
      "# " .. name .. " — jetbrains.nvim",
      "# Generated by :JetbrainsExtras. Do not edit by hand.",
      "",
      "background = " .. c.bg,
      "foreground = " .. c.fg,
      "cursor-color = " .. c.caret,
      "cursor-text = " .. c.bg,
      "selection-background = " .. c.selection,
      "selection-foreground = " .. c.fg,
      "split-divider-color = " .. c.border,
      "",
    }
    for i = 0, 15 do
      lines[#lines + 1] = ("palette = %d=%s"):format(i, ansi[i])
    end
    return table.concat(lines, "\n") .. "\n"
  end,
}
