---@type jetbrains.Extra
return {
  ext = ".conf",
  render = function(c, ansi, name)
    local lines = {
      "# vim:ft=kitty",
      "## name: " .. name,
      "## author: jetbrains.nvim",
      "## Generated by :JetbrainsExtras. Do not edit by hand.",
      "",
      "foreground " .. c.fg,
      "background " .. c.bg,
      "selection_foreground " .. c.fg,
      "selection_background " .. c.selection,
      "cursor " .. c.caret,
      "cursor_text_color " .. c.bg,
      "url_color " .. c.link,
      "",
      "active_border_color " .. c.accent,
      "inactive_border_color " .. c.border,
      "bell_border_color " .. c.warn,
      "",
      "tab_bar_background " .. c.panel,
      "active_tab_foreground " .. c.fg,
      "active_tab_background " .. c.bg,
      "inactive_tab_foreground " .. c.muted,
      "inactive_tab_background " .. c.panel,
      "",
      "mark1_foreground " .. c.on_accent,
      "mark1_background " .. c.accent,
      "mark2_foreground " .. c.fg,
      "mark2_background " .. c.search,
      "mark3_foreground " .. c.fg,
      "mark3_background " .. c.ref_write,
      "",
    }
    for i = 0, 15 do
      lines[#lines + 1] = ("color%d %s"):format(i, ansi[i])
    end
    return table.concat(lines, "\n") .. "\n"
  end,
}
