---@type jetbrains.Extra
return {
  ext = ".yml",
  render = function(c, _, name)
    local function color(v, bold)
      return ('      - "%s"'):format(v) .. (bold and '\n      - "bold"' or "")
    end
    local theme = {
      { "activeBorderColor", c.accent, true },
      { "inactiveBorderColor", c.border },
      { "searchingActiveBorderColor", c.warn, true },
      { "optionsTextColor", c.match },
      { "selectedLineBgColor", c.list_sel },
      { "inactiveViewSelectedLineBgColor", c.caret_row },
      { "cherryPickedCommitFgColor", c.on_accent },
      { "cherryPickedCommitBgColor", c.teal },
      { "markedBaseCommitFgColor", c.bg },
      { "markedBaseCommitBgColor", c.yellow },
      { "unstagedChangesColor", c.vcs.untracked },
      { "defaultFgColor", c.fg },
    }
    local lines = {
      "# " .. name .. " — jetbrains.nvim",
      "# Generated by :JetbrainsExtras. Do not edit by hand.",
      "# Merge into your config.yml, or load with:",
      "#   LG_CONFIG_FILE=~/.config/lazygit/config.yml,~/.config/lazygit/" .. name .. ".yml",
      "gui:",
      "  theme:",
    }
    for _, t in ipairs(theme) do
      lines[#lines + 1] = "    " .. t[1] .. ":"
      lines[#lines + 1] = color(t[2], t[3])
    end
    lines[#lines + 1] = "  authorColors:"
    lines[#lines + 1] = ('    "*": "%s"'):format(c.fg)
    lines[#lines + 1] = "  branchColors:"
    lines[#lines + 1] = ('    "main": "%s"'):format(c.match)
    lines[#lines + 1] = ('    "master": "%s"'):format(c.match)
    return table.concat(lines, "\n") .. "\n"
  end,
}
