---@param c jetbrains.Colors
---@param o jetbrains.Config
return function(c, o)
  return {
    LazyNormal = { link = "NormalFloat" },
    LazyBackdrop = { bg = "#000000", blend = 100 },
    LazyH1 = { fg = c.on_accent, bg = c.accent, bold = true },
    LazyH2 = { fg = c.fg, bold = true },
    LazyButton = { fg = c.fg, bg = c.hover },
    LazyButtonActive = { fg = c.on_accent, bg = c.accent, bold = true },
    LazyComment = { fg = c.comment },
    LazyCommit = { fg = c.muted },
    LazyCommitIssue = { fg = c.link },
    LazyCommitScope = { fg = c.fg, italic = true },
    LazyCommitType = { fg = c.keyword, bold = true },
    LazyDimmed = { fg = c.subtle },
    LazyDir = { fg = c.link, underline = true },
    LazyUrl = { fg = c.link, underline = true },
    LazyProp = { fg = c.field },
    LazyValue = { fg = c.string },
    LazySpecial = { fg = c.keyword },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.orange },
    LazyReasonFt = { fg = c.purple },
    LazyReasonImport = { fg = c.fg },
    LazyReasonKeys = { fg = c.teal },
    LazyReasonPlugin = { fg = c.field },
    LazyReasonRequire = { fg = c.func },
    LazyReasonRuntime = { fg = c.green },
    LazyReasonSource = { fg = c.teal },
    LazyReasonStart = { fg = c.fg },
    LazyProgressDone = { fg = c.ok, bold = true },
    LazyProgressTodo = { fg = c.border },
    LazyNoCond = { fg = c.warn },
    LazyLocal = { fg = c.orange },
    LazyTaskOutput = { fg = c.fg },
    LazyTaskError = { fg = c.error },
  }
end
